name = "ut-folders-stats"
main = "src/index.ts"
compatibility_date = "2026-10-01"
workers_dev = true

[observability]
enabled = false

[triggers]
crons = ["0 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "ut-folders-stats"
database_id = "5da34825-7a70-47b6-955a-e1b75e6d7322"
